views/answer_views.py
from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect
from forms import AnswerForm
from models import Answer

import pymysql

# MySQL 서버에 연결
connection = pymysql.connect(
    host='127.0.0.1',
    user='root',
    password='0000',
    database='flaskproject',
    cursorclass=pymysql.cursors.DictCursor
)

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
def create(question_id):
    form = AnswerForm()
    question = Answer.select_question(question_id)
    if question is None:

        return render_template('404.html'), 404
    if form.validate_on_submit():

        content = request.form['content']
        Answer.insert_answer(question_id, content)
        return redirect(url_for('question.detail', question_id=question_id))
    else:
        return render_template('question/question_detail.html', question=question[0], form=form)

views/question_views.py
import math

from flask import Blueprint,render_template,request, url_for
from models import Question,Answer
from forms import QuestionForm, AnswerForm
from werkzeug.utils import redirect

bp = Blueprint("question",__name__, url_prefix="/question")

@bp.route('/list/')
def _list():

    page = request.args.get('page', type=int, default=1)

    ## 직접 주소창에 페이지 입력하는 경우 1보다 작으면 1로 가게끔
    if int(page) <1:
        page = 1

    question_list = Question.select_all_order_list()

    ###하드코딩 주의!!!!!!!!!!!!!!!#######################
    ##모듈화 하면 좋겠지만...일단 이렇게 구현
    pagination = {}
    pagination['items'] = question_list
    pagination['count'] = len(question_list) ## 총 개수 보관용
    pagination['per_page'] = 10  ## 원하는 개수만큼 조정
    pagination['total'] = len(question_list) // pagination['per_page'] +1 if len(question_list) % pagination['per_page']  != 0 else len(question_list) // pagination['per_page']
    pagination['current_page'] = page


    if pagination['total'] > 10 and pagination['current_page'] <=5 :
        pagination['iter_pages'] = list(range(1, 11))
    elif pagination['total'] > 10 and pagination['current_page'] + 4 >= pagination['total']:
        # 현재 페이지 기준으로 마지막 10개 페이지 출력
        pagination['iter_pages'] = list(range(pagination['current_page'] - 9, pagination['total'] + 1))
    elif pagination['total'] > 10 :
        pagination['iter_pages'] = list(range(pagination['current_page'] - 4, pagination['current_page'] + 6))
    else :
        # 10페이지보다 적은 경우
        pagination['iter_pages'] = [i + 1 for i in range((pagination['total']))]

   ### 답변 개수 산출용
    for item in pagination['items']:
        item['count'] = Answer.how_many_answers(item['id'])


    pagination['prev_num'] = pagination['current_page'] - 1
    pagination['next_num'] = pagination['current_page'] + 1
    pagination['has_prev'] = pagination['current_page'] > 1
    pagination['has_next'] = pagination['current_page'] < pagination['total']

    ## 다음페이지가 있고 개수가 10개 안 되는 경우
    if (pagination['has_next'] and len(question_list) % pagination['per_page'] != 0):
        pagination['items'] = question_list[  (pagination['current_page']-1) * pagination['per_page'] :  pagination['current_page'] * pagination['per_page']]
    ## 현재 페이지가 마지막 페이지이며, 하나밖에 없는 경우
    elif(len(pagination['iter_pages'])==1 ):
        pagination['items'] = question_list
    else:
        pagination['items'] = question_list[(pagination['current_page'] - 1) * pagination['per_page']: ]

    question_list = pagination


    return render_template('question/question_list.html', question_list=question_list)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.select_one(question_id)
    if question is None:
        return render_template('404.html'), 404
    question = dict(question)

    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = QuestionForm()

    if request.method == 'POST' and form.validate_on_submit():
        subject = form.subject.data
        content = form.content.data
        Question.insert_question(subject,content)
        return redirect(url_for('main.index'))

    return render_template('question/question_form.html', form=form)

templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question['subject'] }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question['content'] }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question['create_date']|datetime }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 목록 -->
    <h5 class="border-bottom my-3 py-2">{{ question['answer_set']|length }}개의 답변이 있습니다.</h5>
    {% for answer in question['answer_set'] %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer['content'] }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer['create_date']|datetime }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question['id']) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->



        <div class="mb-3">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="my-3">
            {{ form.csrf_token }}
<!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
  <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.data or '' }}">
        </div>
        <div class="mb-3">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.data or '' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>

    </form>
    <a href={{url_for('main.index')}}><button class="btn btn-primary">뒤로 가기</button></a>
</div>
{% endblock %}

templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>

        {% if question_list %}
        {% for question in question_list['items'] %}
        <tr>

            <td>{{ question_list['count']- ((question_list['current_page']-1) * question_list['per_page']) - loop.index0 }}</td>
            <td>
                <a href="{{ url_for('question.detail', question_id=question['id']) }}">{{ question['subject'] }}</a>
                {% if question['count'] > 0 %}
                <span class="text-danger small mx-2">{{ question['count'] }}</span>
                {% endif %}
            </td>
            <td>{{ question['create_date']|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>


  <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list['has_prev'] %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list['prev_num'] }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지번호 -->
        {% for page_num in question_list['iter_pages'] %}
        {% if page_num %}
        {% if page_num != question_list['current_page'] %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list['has_next'] %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list['next_num'] }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->



    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}