views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request
from werkzeug.security import generate_password_hash
from werkzeug.utils import redirect

from forms import UserCreateForm
from models import User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.select_one(username=form.username.data)
        if not user:
            User.create_user(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            return redirect(url_for('main.index'))

        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>물어보시라~ | 게시판</title>

    <link rel="stylesheet" type="text/css" href = "{{ url_for('static', filename="bootstrap.min.css")}}" >
    <link rel="stylesheet" type="text/css" href = "{{ url_for('static', filename="my_style.css")}}" >
    <!-- 구글폰트 -->
    <link href="https://fonts.googleapis.com/css?family=Stylish&display=swap" rel="stylesheet">
    <!-- Bootstrap JS -->
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}

<!-- 각자 페이지 시작 -->
{% block content %}
{% endblock %}
<!--각자 페이지 line 끝 -->
</body>
</html>

templates/form_errors.html
<!-- 필드오류 -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {% for field, errors in form.errors.items() %}
    <strong>{{ form[field].label }}</strong>
    <ul>
        {% for error in errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
{% endif %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">D·WHY</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("auth.signup") }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>